import { cinzel, openSans } from '@/components/ui/fonts/fonts'
import Header from '@/components/ui/layout/header/header'
import '@/styles/globals.css'
import type { Metadata } from 'next'
export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html
            lang="pt-br"
            className={`${cinzel.variable} ${openSans.variable} `}
        >
            <body className="font-openSans">
                <Header />
                {children}
            </body>
        </html>
    )
}
